### ISSUE TITLE
Using with other pg packages

### ISSUE THREAD

**Issue by uLan08** [voxpelli/node-pg-pubsub#14]
I am not really sure where to post this. I wan't to use this package but I am already using another node pg package extension, specifically this [one](https://github.com/langpavel/node-pg-async).

How will I use this package together with the other one? Will doing something like this suffice and not seem redundant? 
```
const pgAsync = new PgAsync(uri)
const pgPubSub = new PGPubsub(uri)
```
If so, are there any implications in implementing it like this?

**Comment by voxpelli** [comment]
It works perfectly well to use this library with any other pg package.

This library uses it's own persistent connection to subscribe to messages and that connection is always independent of any other connections in a general pg libraries connection pool and such, so there are really no interactions between the two at all.

Only minor minor benefit of using the same version of the `pg` module as this module is that it would be deduped on install, but that's very minor and should really be neglected.

One thing to note though – as stated in the documentation it is better to send your messages using your main library than with the `publish()` method of this library – that's because then it will use the connection pool of your main library rather than the connection of this library, which should be faster. That's the case no matter which other `pg` module you use though, `publish()` is only there for the sake of completeness – so that one can use this module fully on its own without having to rely on anything else for any part of things.

**Comment by uLan08** [comment]
Oh okay. Thanks for the heads up. Do you might know how to implement that? Or perhaps could you link me to the part of the documentation where it says that and I'll dig around from there.

**Comment by voxpelli** [comment]
@uLan08 How to send messages using another library? It's right there in the README: `NOTIFY channelName, '{"hello":"world"}'`

Just switch `channelName` to whatever channel you want to publish your message to and the `{"hello":"world"}` to whatever JSON or non-JSON message you want to post. (Just ensure that the JSON is properly escaped so that you don't expose yourself to SQL-injections)

**Comment by uLan08** [comment]
Oh I completely failed to comprehend your reply earlier. I am publishing messages perfectly fine and yes I am sending it from my main library. What I actually am having trouble is with subscription and capturing the message payload and that is what I will be using this library for. So that will be the `addChannel` function. If there are really no implications in using another connection pool for listening then all is good.

**Comment by voxpelli** [comment]
That should work superb 👍
