### ISSUE TITLE
pg is not listed as an npm dependency

### ISSUE THREAD

**Issue by nbibler** [voxpelli/node-pg-pubsub#2]
While the library performs a `require('pg')`, the `package.json` does not include a requirement for the `pg` library.

**Comment by voxpelli** [comment]
That's for historical reasons, as previously it accepted both `pg.js` and `pg`, so to leave the choice to the consumer it didn't include either of them as dependencies.

Now that the `pg`-project has changed so that everything is done through the `pg` module you're right that it makes sense to add it.
